apiVersion: v1
kind: Secret
metadata:
  name: campus-secrets
type: Opaque
stringData:
  mysql-root-password: "campus123456"
  mysql-user-password: "campus_user_pass"
  jwt-secret: "campus-micro-mart-jwt-secret-key-2024-must-be-long-enough"
  redis-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
